// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VersionManagement.Repositories;

namespace PackageTest.Migrations
{
    [DbContext(typeof(VersionDbContext))]
    [Migration("20190129014633_UpdateVersion")]
    partial class UpdateVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VersionManagement.Models.VersionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Applicant")
                        .IsRequired();

                    b.Property<string>("CommitIds")
                        .IsRequired();

                    b.Property<string>("DetailNote");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Iteration")
                        .IsRequired();

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("TaskTitle")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.Property<int>("VersionId");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("VersionManagement.Models.VersionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Creator")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("ReleaseNote");

                    b.Property<int>("Status");

                    b.Property<string>("VersionNumber")
                        .IsRequired();

                    b.Property<string>("VersionTitle")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("VersionManagement.Models.VersionDetail", b =>
                {
                    b.HasOne("VersionManagement.Models.VersionInfo", "Version")
                        .WithMany("Detailes")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
