// <auto-generated />
using System;
using EnterpriseOrganization.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PackageTest.Migrations.OrgDb
{
    [DbContext(typeof(OrgDbContext))]
    [Migration("20190213020736_AddChangeId")]
    partial class AddChangeId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnterpriseOrganization.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiveChangeId");

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("CompanyId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("DirectorId");

                    b.Property<string>("EmployeeIds");

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ParentId");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
