// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilsPack.Repositories;

namespace PackageTest.Migrations.UtilDb
{
    [DbContext(typeof(UtilDbContext))]
    partial class UtilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UtilsPack.Models.ChangeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChangedProperties");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool?>("IsActive");

                    b.Property<int>("OperationType");

                    b.Property<int>("RecordType");

                    b.Property<string>("SourceId")
                        .IsRequired();

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("ChangeRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
